// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG8y4GZF-SV7K0HUg-AfMRS0e22hsXqdQ',
    appId: '1:870946837687:web:c66e24e6376f3e94cae932',
    messagingSenderId: '870946837687',
    projectId: 'twitter27mart',
    authDomain: 'twitter27mart.firebaseapp.com',
    databaseURL: 'https://twitter27mart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitter27mart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0LAzswVPbunNGATSozvcMxOyuuwaKiew',
    appId: '1:870946837687:android:d48798e026b50b29cae932',
    messagingSenderId: '870946837687',
    projectId: 'twitter27mart',
    databaseURL: 'https://twitter27mart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitter27mart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQnYQxl9MrEpmYYFlYAZFFTtCXfvPPAjU',
    appId: '1:870946837687:ios:f67e819166bdb573cae932',
    messagingSenderId: '870946837687',
    projectId: 'twitter27mart',
    databaseURL: 'https://twitter27mart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitter27mart.appspot.com',
    iosClientId: '870946837687-pme6k2cicci7ammcoacjrsnip04hm9j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQnYQxl9MrEpmYYFlYAZFFTtCXfvPPAjU',
    appId: '1:870946837687:ios:f67e819166bdb573cae932',
    messagingSenderId: '870946837687',
    projectId: 'twitter27mart',
    databaseURL: 'https://twitter27mart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twitter27mart.appspot.com',
    iosClientId: '870946837687-pme6k2cicci7ammcoacjrsnip04hm9j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );
}
